### ISSUE TITLE
Review for JOSS

### ISSUE THREAD

**Issue by Fil** [KMarkert/cartoee#1]
Ref. https://github.com/openjournals/joss-reviews/issues/1207

- [x] version number mismatch: you have published release `0.03` (on github) where it should be `0.0.3` (like on pip)

- [x] installation / list of dependencies: I've tried installing with jupyter lab/python3 ~and I get an error from ee indicating that it's probably only compatible with python2. Is this correct, and can you clarify this situation? Please mention that ee is a dependency too (even if that's pretty obvious).~

(That's all I can say for now. I'll be back later if I manage to install it.)

**Comment by KMarkert** [comment]
Thanks for the review @Fil! 

version number mismatch: I believe that all of the versions between github, pip, and zenodo are version 0.03. Can you please clarify where the versions are mismatched and I will fix the mismatch?

installation / list of dependencies: the ee package should work with python3 (that is what I have been using). The fact that ee is a dependency is mentioned in the documentation [here](https://cartoee.readthedocs.io/en/latest/introduction.html#dependencies) and can be installed using `pip install earthengine-api`. Can you please clarify what the error message was that you received for the installation and I may help.

**Comment by Fil** [comment]
The mismatch is the presence of a dot. On github the release is 0.03 and in pip I got cartoee (0.0.3)

`pip install cartoee` did not install all the necessary packages for some reason

Maybe I made a mistake when I thought I should `pip install ee`
now I've tried  `pip install cartoee earthengine-api` instead, and I receive

> ModuleNotFoundError: No module named 'oauth2client'
then same error with cartopy, then

ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject


I'm not necessarily giving up, but not at the point where I can test things on my computer.

Have just tried taking a different route with a colaboratory notebook, and I get the same error again, as if the dependencies were not recognized

![capture d ecran 2019-01-28 a 21 00 19](https://user-images.githubusercontent.com/7001/51862876-e09fed80-233f-11e9-8618-dc9eb94e41cd.png)

**Comment by KMarkert** [comment]
Thank you for pointing out that detail. Please confirm that I have fixed all of the mismatched versions (should be 0.0.5 now).

As for the installation, I have added into the setup.py the `install_requires` argument so that all of the Python dependencies will be installed as well. However, the cartopy package will need GEOS and Proj4 libraries installed prior to running `pip install cartoee`. If those libraries are not installed the cartoee install will fail; I have noted this in the [documentation](https://cartoee.readthedocs.io/en/latest/introduction.html#dependencies). The "ValueError: numpy.ufunc size changed" error was also due to dependency's latest version, I fixed the required version of cartopy to be 0.16.0 to circumvent that error for now.

An example Colab notebook for installation and testing the installation can be found at this link: https://colab.research.google.com/drive/1pvDOKC7QLLeOGGLBlFgZwcp6FNde1DhI

Thank you for bearing with me on the installation part.

**Comment by Fil** [comment]
Excellent! No problem, it's my job as a JOSS reviewer to make sure things install smoothly.

**Comment by Fil** [comment]
All checked 🎉
